short: phonological and full-text layers in multiple transcriptions

description: >-
  <p>Phonetic search interface for <a id="corpus2link" href="#"></a>.</p>
  <p>This search interface is by:</p>
  <ul>
      <li><a id="author2link" href="#"></a> («author2.role»)
      <li><a id="author1link" href="#"></a> («author1.role»)
  </ul>

defaultSettings:
  autoexec: true
  nodeseq: true
  exporthl: true
  exportsr: true
  multihl: true
  simple: false

defaultFlags:
  i: true
  m: true
  s: false

keyboard:
  'š': '$'
  'č̣': '%'
  'k̭': '&'
  'ʿ': '('
  'ʾ': ')'
  'č̭': '*'
  'ṱ': '+'
  'ŭ': '2'
  'ɛ': '3'
  'ɟ': '4'
  'č': '5'
  'ð': '6'
  'ð̣': '6.'
  'ž': '7'
  'θ': '8'
  'ə': '9'
  'č': '>c'
  'č̣': '>c.'
  'č̭': '>c<'
  'š': '>s'
  'ž': '>z'
  'ă': '@'
  'ā': 'A'
  'ḍ': 'D'
  'ē': 'E'
  'ġ': 'G'
  'ḥ': 'H'
  'ī': 'I'
  'ḷ': 'L'
  'ṃ': 'M'
  'ō': 'O'
  'p̣': 'P'
  'ṛ': 'R'
  'ṣ': 'S'
  'ṭ': 'T'
  'ū': 'U'
  'ẓ': 'Z'
  'ð̣': '^'
  'á': "a'"
  'ɑ': 'a'
  'ā́': "a-'"
  'ā': 'a-'
  'ā̀': 'a-`'
  'ắ': "a>'"
  'ă': 'a>'
  'ằ': 'a>`'
  'à': 'a`'
  'c̭': 'c<'
  'ḍ': 'd.'
  'ē': 'e-'
  'ġ': 'g.'
  'ḥ': 'h.'
  'ı': 'i~'
  'ī': 'i-'
  'ĭ': 'i>'
  'k̭': 'k<'
  'ḷ': 'l.'
  'ṃ': 'm.'
  'ō': 'o-'
  'p̣': 'p.'
  'p̌': 'p<'
  'p̭': 'p<'
  'ṛ': 'r.'
  'ṣ': 's.'
  'ṭ': 't'
  'ṱ': 't<'
  'ū': 'u-'
  'ŭ': 'u<'
  'ẓ': 'z.'

layerSettings:
  word:
    description: Some words are affixed to others without intervening space.
    layers:
      text:
        afterDefault: /
        afterFeature: text_end
        default: ¿
        description: text precise, complete, uses non-ascii
        feature: text
        pos: null
        visible: true
      full:
        afterDefault: /
        afterFeature: full_end
        default: ¿
        description: text representation
        feature: full
        pos: null
        visible: false
      fuzzy:
        afterDefault: /
        afterFeature: fuzzy_end
        default: ¿
        description: text representation
        example: mute
        feature: fuzzy
        pos: null
        visible: true
      lite:
        afterDefault: /
        afterFeature: lite_end
        default: ¿
        description: text representation
        feature: lite
        pos: null
        visible: false
      cls:
        afterDefault: /
        afterFeature: fuzzy_end
        default: z
        descend: letter
        description: phonetic class
        feature: phonetic_class
        pos: null
        visible: false
      voice:
        afterDefault: /
        afterFeature: fuzzy_end
        default: z
        descend: letter
        description: phonation
        feature: phonation
        pos: cls
        visible: false
      place:
        afterDefault: /
        afterFeature: fuzzy_end
        default: z
        descend: letter
        description: phonetic place
        feature: phonetic_place
        pos: cls
        visible: false
      manner:
        afterDefault: /
        afterFeature: fuzzy_end
        default: z
        descend: letter
        description: phonetic manner
        feature: phonetic_manner
        pos: cls
        visible: false
      pos:
        afterDefault: /
        afterFeature: fuzzy_end
        default: z
        description: part-of-speech
        feature: pos
        pos: null
        visible: false
      lang:
        afterDefault: /
        afterFeature: fuzzy_end
        default: 0
        description: language, indicated by a number
        feature: lang
        pos: null
        tip: true
        visible: false
      speaker:
        afterDefault: /
        afterFeature: fuzzy_end
        default: 0
        description: speaker, indicated by a number
        feature: speaker
        pos: null
        tip: true
        visible: false
  sentence:
    afterDefault: "\n"
    focus: true
    description: Sentences are delimited by full stops.
  line:
    afterDefault: "\n"
    description: Lines are really paragraphs.
    layers:
      number:
        default: -1
        description: line number
        feature: line_number
        pos: null
        visible: false
  text:
    afterDefault: "\n"
    description: Texts are stories, having some metadata, consisting of lines.
    layers:
      title:
        default: ¿
        description: title of a text
        example: A
        feature: title
        pos: null
        visible: false
      tid:
        default: ¿
        description: id of a text
        feature: text_id
        pos: null
        visible: false
      dialect:
        ascend: dialect
        default: ¿
        description: dialect of a text <code>Barwar Urmi_C</code>
        feature: dialect
        pos: null
        visible: false
      place:
        default: ¿
        description: place of a text
        example: Dure
        feature: place
        pos: null
        visible: false
